# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-19 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Item ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Item Name')),
                ('descript', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Item Descript')),
                ('type', models.CharField(blank=True, choices=[('arcane', 'arcane'), ('rune', 'rune'), ('curse', 'curse'), ('cloak', 'cloak'), ('other', 'other')], db_index=True, default='other', max_length=64, null=True, verbose_name='Item Type')),
                ('info', models.TextField(blank=True, default='', null=True, verbose_name='Item Info Json')),
            ],
            options={
                'verbose_name': 'Item Data',
                'verbose_name_plural': 'Item Data',
                'db_table': 'WOLH_items',
            },
        ),
    ]
