# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-19 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Operation ID')),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Operation Time')),
                ('user', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Operatopm User Name')),
                ('operation', models.CharField(default='', max_length=256, verbose_name='Operatopm Type')),
                ('info', models.TextField(blank=True, default='', null=True, verbose_name='Operation Info Json')),
            ],
            options={
                'verbose_name': 'Operation Record',
                'verbose_name_plural': 'Operation Record',
                'db_table': 'WOLH_operations',
            },
        ),
    ]
