# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-19 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_manage', '0002_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='type',
            field=models.CharField(blank=True, choices=[('arcane', '奥术'), ('rune', '符文'), ('curse', '诅咒'), ('cloak', '斗篷'), ('other', '其他')], db_index=True, default='other', max_length=64, null=True, verbose_name='Item Type'),
        ),
    ]
