# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-19 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_manage', '0004_auto_20180619_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': '道具信息', 'verbose_name_plural': '道具信息'},
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': '操作记录', 'verbose_name_plural': '操作记录'},
        ),
        migrations.AlterField(
            model_name='items',
            name='descript',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='道具描述'),
        ),
        migrations.AlterField(
            model_name='items',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='道具ID'),
        ),
        migrations.AlterField(
            model_name='items',
            name='info',
            field=models.TextField(blank=True, default='', null=True, verbose_name='道具信息Json'),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(db_index=True, max_length=256, unique=True, verbose_name='道具名'),
        ),
        migrations.AlterField(
            model_name='items',
            name='type',
            field=models.CharField(blank=True, choices=[('arcane', '奥术'), ('rune', '符文'), ('curse', '诅咒'), ('cloak', '斗篷'), ('other', '其他')], db_index=True, max_length=64, null=True, verbose_name='道具类型'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='操作ID'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='info',
            field=models.TextField(blank=True, default='', null=True, verbose_name='操作信息Json'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation',
            field=models.CharField(default='', max_length=256, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='user',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='操作用户'),
        ),
    ]
